let productsDB = [
    {
    id: 1,
    title: "Men's Jacket",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/jacket-1.jpg",
    stock: "in Stock",
    brand: "ZARA",
    category: "Jacket",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 2,
    title: "Wall Clock",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/watch-3.jpg",
    stock: "in Stock",
    brand: "RADO",
    category: "Watches",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 3,
    title: "Boot shoe",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/shoe-5.jpg",
    stock: "Last Stock",
    brand: "CAT",
    category: "Shoes",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 4,
    title: "Summer Short",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/shorts-1.jpg",
    stock: "in Stock",
    brand: "ADIDAS",
    category: "Clothes",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 5,
    title: "Sports Shoe",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/sports-6.jpg",
    stock: "Last Stock",
    brand: "NIKE",
    category: "Shoes",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 6,
    title: "Winter Jacket",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/jacket-6.jpg",
    stock: "Last Stock",
    brand: "OR",
    category: "Jacket",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 7,
    title: "Perfume Women",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/perfume.jpg",
    stock: "Last Stock",
    brand: "DIOR",
    category: "Accessories",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 8,
    title: "Bkue Shirt",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/shirt-1.jpg",
    stock: "in Stock",
    brand: "LC Wikiki",
    category: "Clothes",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 9,
    title: "Apple Watch",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/watch-2.jpg",
    stock: "in Stock",
    brand: "Apple",
    category: "Watches",
    isMe: "N",
    qty: 1,
    
  },
  {
    id: 10,
    title: "Apple Watch",
    desc: "Lorem Ipsum, Dolor Sit Amet Consectetur Adipisicing Elit. Blanditiis, Veniam?",
    price: 12.99,
    imageUrl: "images/watch-2.jpg",
    stock: "in Stock",
    brand: "Apple",
    category: "Accessories",
    isMe: "N",
    qty: 1,
    
  },
]


// localStorage.setItem("products", JSON.stringify(productsDB));